name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-readme-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: amitpaul2004

      - name: Commit & Push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add -A .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update 3D contribution graph [skip ci]"
            git push
          fi
